##########################################################################################################################
##############
##############     Script to extract NCI values for each tree in a plot given the position,
##############      size and identity of neighbors   
##############
##############      Aitor Ameztegui, CREAF - CTFC
##############      ameztegui@gmail.com
##############      February, 2016
##############
#################################################################################################################################


nci_extract <- function (targets, alpha, beta, lambda = 1, min.target.dbh = 9, min.neighbor.dbh = 9, max.neighbor.radius = 20)  { 

### This function requires 3 parameters, and 4 more are optional
        # targets: the dataframe containing the tab-delimited tree map.
        # alpha: the exponent for the DBHs
        # beta: the exponent for the distances
        # gamma: the species j NCI Lambda. By default, it takes value 1
        # min.target.dbh: Minimum target tree DBH, in cm. By default, takes value 9 cm
        # min.neighbor.dbh: min. neighbor tree, in cm. By default, it takes value 9 cm
        # max.neighbor.radius: NCI Maximum Crowding Distance, in meters (default = 20 m)
        
### The dataset "targets" is the tab-delimited file generated by SORTIE. It will tipycally contain 6 columns, although it may contain more 
### depending on the specifications of the detailed output. 
### It is important to ensure that the names of the variables exactly match the names below, 
### and that the units are right. Otherwise, scale them prior to calculations.
###
###       X : X coordinate (m)
###       Y : Y coordinate (m)
###       Species
###       Type: Seedling/Sapling/Adult/Snag
###       Diam: diameter of the target tree (cm)
###       Height: height of the targer tree (m)



# Generate the required files ---------------------------------------------

### To calculate NCI, we need information on the identity, dimensions and position of all the neighbors for each target tree
### All the neighbors for each target tree must be ordered in columns, each row being a target tree

        # Generate the species data frame
        species <- matrix(rep(targets[,"Species"], length(targets[,"Species"])), ncol=length(targets[,"Species"]), byrow = T )

        # Generate the dbhs data frame
        dbhs<-matrix(rep(targets[,"Diam"], length(targets[,"Diam"])), ncol=length(targets[,"Diam"]), byrow = T )
        
        # Generate the distances data frame
        x_matrix<-matrix(rep(targets[,"X"], length(targets[,"X"])), ncol=length(targets[,"X"]), byrow = T )
        y_matrix<-matrix(rep(targets[,"Y"], length(targets[,"Y"])), ncol=length(targets[,"Y"]), byrow = T )
        xdist_matrix <- x_matrix - targets[,"X"]
        ydist_matrix <- y_matrix - targets[,"Y"]
        distances <- sqrt(xdist_matrix^2 + ydist_matrix^2)

        # Delete the target tree (it does not compete with itself!)

        for (i in 1 : nrow(targets)) {
                distances [i,i]<- NA
                dbhs [i,i]<- NA
                species [i,i]<- NA
        }


# Set up some limits for the analysis -------------------------------------

        # Create a vector that contains {TRUE or FALSE} for whether each observation meets all of your criteria
        using.targets <- which(targets[,"Diam"] >= min.target.dbh)
        
        targets <- targets[using.targets,]  
        dbhs <- dbhs[using.targets,]
        distances <- distances[using.targets,]
        species <- species[using.targets,]
        
        # Within each row, get rid of neighbors under the minimum DBH
        #   dbhs are in meters in this matrix (for use in NCI)
        dbhs <- ifelse(dbhs < min.neighbor.dbh, 0, dbhs)       
        
        # Get rid of neighbors beyond the max radius
        distances <- ifelse(distances > max.neighbor.radius, 0, distances)
        dbhs[which(distances == 0)] <- 0
        distances[which(dbhs == 0)] <- 0
        
        # Convert columns with 0 for distance to missing values (NA)
        distances <- ifelse(distances == 0, NA, distances)
        

# Compute NCI -------------------------------------------------------------

        nci <- rowSums(lambda*(dbhs ^ alpha)/(distances ^ beta), na.rm=T)
        newtargets <- cbind(targets, nci)
        return(newtargets)
        
}

# Example for Pinus sylvestris

nci_extract (targets , alpha = 1.79, beta = 0.61,lambda = 0.81)



